site_name: Pipipi's Notebook
site_url: https://notebook.foreverhyx.top
repo_name: ForeverHYX/Notebook
repo_url: https://github.com/ForeverHYX/Notebook
edit_uri: tree/master/docs
site_description: Pipipi's Notebook
copyright: Copyright &copy; 2022-2025 <a href="https://github.com/ForeverHYX" target="_blank" rel="noopener">ForeverHYX</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default
